# Generated by Django 5.2.6 on 2025-09-26 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
        ('projects', '0003_alter_project_options_alter_projectmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Content of the comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(help_text='Issue this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the comment was last updated'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='User assigned to resolve this issue (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the issue was created'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(help_text='Detailed description of the issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text='Project this issue belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(help_text='User who reported this issue', on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', help_text='Current status of the issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Brief title describing the issue (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the issue was last updated'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['issue'], name='issues_comm_issue_i_bf5083_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='issues_comm_author__187c55_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='issues_comm_created_2cc4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project'], name='issues_issu_project_05d549_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='issues_issu_status_003ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority'], name='issues_issu_priorit_77f54b_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assignee'], name='issues_issu_assigne_32a375_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='issues_issu_created_6f38eb_idx'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='issues_comment',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issues_issue',
        ),
    ]
