# Generated by Django 5.2.6 on 2025-09-26 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Project Member', 'verbose_name_plural': 'Project Members'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the project was created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the project was last updated'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined the project'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(help_text='Project the user is a member of', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='member', help_text='Role of the user in the project', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(help_text='User who is a member of the project', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_pr_owner_i_dea3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'user'], name='projects_pr_project_9c82c6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['role'], name='projects_pr_role_094dc1_idx'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects_project',
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='projects_projectmember',
        ),
    ]
